# -*- coding: utf-8 -*-
"""pandas_basic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nxNEjpPe7VWZRbNkb7RApMa95sY6f-nR
"""

import pandas as pd
import numpy as np

data = pd.read_csv("/content/FashionDataset.csv")
df = pd.DataFrame(data)
df

df.head()

df.tail()

data.info()

print(df.shape)
print(df.size)
print(df.ndim)

df.columns

df.drop(columns="Unnamed: 0", inplace=True)

df

df.columns

df.rename(columns={"Deatils":"Details"}, inplace = True)

df.columns

df.duplicated().value_counts()

df.duplicated().sum()

df.drop_duplicates(inplace = True)

df.duplicated().sum()

df = df.reset_index().drop(columns= "index")

df

df.isna().sum()

df.dropna(inplace =True,)

df.isna().sum()

df

df["BrandName"] = df["BrandName"].apply(lambda x:x.capitalize())

df["Details"] = df["Details"].apply(lambda x:x.capitalize())

df

df["Sizes"] = df["Sizes"].replace("Nan","NA VALUED")

df = df[df['Sizes'] !="NA VALUED"]
df = df[df['MRP'] !="Nan"]

df["Discount"] = df["Discount"].replace("Nan","No Discount")

df = df.reset_index().drop(columns = "index")

df

df.to_csv("Cleaned_data.csv")